# frozen_string_literal: true

# This file is generated by ruby-bindgen during development/build via:
#   bundle exec rake bindings:generate
# It is checked in so consumers of the gem do not need ruby-bindgen.

module Llama
  extend FFI::Library
  ffi_lib ENV.fetch('LLAMA_CPP_LIB', 'llama')

  # Placeholder fallback. The real file should be generated from llama.h.
  # We keep one stable function so requiring the gem works before generation.
  attach_function :llama_max_devices, [], :int
end
